#executar no cmd: docker-compose up

version: '2.2'
services:

  banco_de_dados:
      image: postgres
      ports:
        - "5432:5432"    
      environment:
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=123456789
          - POSTGRES_DB=db_cep
      volumes:
          - flask_polls_data:/var/lib/postgresql/data
      networks:
        elastic:
          ipv4_address: 172.28.1.8


  flask:
    build: .
    ports:
      - "5000:5000"    
    networks:
      elastic:
        ipv4_address: 172.28.1.9

volumes:
    flask_polls_data:

networks:
  elastic:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
